---
title: "mathstat"
author: "Dr. Joseph McKean"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Overview
This package illustrates the applicability of the concepts and alogrithms covered in 8th edition of the text *Introduction to Mathematical Statics* by Hogg, McKean, and Craig (2018). The topics in which these functions apply to includes but are not limited to the following:

1. Probability and Distributions
1. Multivariate Distributions
1. Some Special Distributions 
1. Some Elementary Statistical Inferences 
1. Consistency and Limiting Distributions
1. Maximum Likelihood Methods
1. Sufficiency 
1. Optimal Test of Hypothesis 
1. Inference About Normal Linear Models
1. Nonparametric and Robust Statistics
1. Bayesian Statistics

Below consists of the list of function within the mathstat package.

## Functions

<center> <h2>--A--</h2> </center>
[abgame](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/abgame.html) <center>Coin Flip versus Die Roll Game</center>
<br>
[aresimcn](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/aresimcn.html) <center>A Relative Efficency Investigation Simulation</center>

<center> <h2>--B--</h2> </center>
[bday](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/bday.html) <center>Birthday Solver</center>
<br>
[betaplts](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/betaplts.html) <center>Beta Distribution Plots</center>
<br>
[binomci](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/binomci.html) <center>Binomial distribution Confidence Interval</center>
<br>
[binompower](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/binompower.html) <center>Power Functions for Binomial Tests</center>
<br>
[bootstrapcis64](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/bootstrapcis64.html) <center>Percentile Bootstrap Confidence Interval</center>
<br>
[boottestonemed](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/boottestonemed.html) <center>Bootstrap Test One Median</center>
<br>
[boottesttwo](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/boottesttwo.html) <center></center>

<center> <h2>--C--</h2> </center>
[chistable](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/chistable.html) <center>Chi-Square Distribution</center>
<br>
[cipi](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/cipi.html) <center>Confidence Interval and Predictive Interval for Linear Models</center>
<br>
[condsim1](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/condsim1.html) <center>Observation Generator</center>

<center> <h2>--D--</h2> </center>
[data](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/data.html) <center>AZT doses</center>
<br>
[dcn](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/dcn.html) <center>PDF of Contaminated Normal</center>
<br>
[dex165](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/dex165.html) <center>Probability Mass Function for Exercise 1.6.5</center>
<br>
[dlogF](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/dlogF.html) <center>Density of Log Distribution</center>
<br>
[dloggamma](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/dloggamma.html) <center>Density of Log Gamma Distribution</center>

<center> <h2>--E--</h2> </center>
<br>
[ellipmake](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/ellipmake.html) <center>Plot Ellipse</center>
<br>
[empalphacn](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/empalphacn.html) <center>Emperical Alpha</center>
<br>
[ex158](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/ex158.html) <center>Piecewise CDF Graph</center>
<br>
[ex1427](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/ex1427.html) <center>Number Drawing Game</center>

<center> <h2>--F--</h2> </center>
[fp1](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/fp1.html) <center>F-Distribution Table for Upper 0.05 Critical Points</center>
<br>
[fp2](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/fp2.html) <center>F-Distribution Table for Upper 0.05 Critical Points</center>
<br>
[fp3](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/fp3.html) <center>F-Distribution Table for Upper 0.01 Critical Points</center>
<br>
[fp4](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/fp4.html) <center>F-Distribution Table for Upper 0.01 Critical Points</center>
<br>
[ftable](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/ftable.html) <center>F-Distribution Table for 0.05, 0.25, and 0.01 Critical Points</center>

<center> <h2>--G--</h2> </center>
[getcis](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/getcis.html) <center>Get Confidence Intervals</center>
<br>
[gibbser2](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/gibbser2.html) <center>Gibbs Sampler</center>
<br>
[gibbser3](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/gibbser3.html) <center>Gibbs Sampler with Bayesian Inference</center>

<center> <h2>--H--</h2> </center>
[hcplot](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/hcplot.html) <center></center>
<br>
[hierarch1](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/hierarch1.html) <center>Hierarchal Bayes Model</center>

<center> <h2>--M--</h2> </center>
[mcpbon](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/mcpbon.html) <center>Bonferroni's Multiple Comparisons Procedure</center>
<br>
[mcpfisher](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/mcpfisher.html) <center>Fisher's Protected Least Significance Difference</center>
<br>
[mixnormal](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/mixnormal.html) <center>The First Iteration of the EM Step</center>
<br>
[mlelogistic](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/mlelogistic.html) <center>MLE Estimation of Location Based on a Logistic Distribution</center>
<br>
[mses](http://www.stat.wmich.edu/mckean/Prjhmcpkg/Manpages/mses.html) <center>Mean Squared Error</center>
<br>
[multitrial](man/multitrial.Rd) <center>Multinomial Trial Simulation</center>

<center> <h2>--N--</h2> </center>
[newfigc3s3.1](man/newfigc3s3.1.Rd) <center>Figure 3.3.1</center>
<br>
[normaltable](man/normaltable.Rd) <center>Normal Distribution Table</center>

<center> <h2>--O--</h2> </center>
[onesampsgn](man/onesampsgn.Rd) <center>One-Sample Sign Analysis</center>

<center> <h2>--P--</h2> </center>
[pcn](man/pcn.Rd) <center>Probability of Contaminated Normal (CDF)</center>
<br>
[percentciboot](man/percentciboot.Rd) <center>Percent Confidence Interval bootstrap</center>
<br>
[piest](man/piest.Rd) <center>Estimation of Pi Using Binomial Experiment</center>
<br>
[piest2](man/piest2.Rd) <center>Estimation of Pi by Monte Carlo Integration</center>
<br>
[plifetime](man/plifetime.Rd) <center>Probability of Battery Lifetime</center>
<br>
[plogF](man/plogF.Rd) <center>Probability of Log Distribution</center>
<br>
[ploggamma](man/ploggamma.Rd) <center>PDF of Mixture Distribution</center>
<br>
[plotsulfur](man/plotsulfur.Rd) <center>Plot Sulfurdioxide</center>
<br>
[pltlogF](man/pltlogF.Rd) <center>Plot Log Function</center>
<br>
[poisrand](man/poisrand.Rd) <center>Simulating Poisson Processes</center>
<br>
[poissonci](man/poissonci.Rd) <center>Confidence Interval for mean of of a Poisson Distribution</center>
<br>
[poissontable2](man/poissontable2.Rd) <center></center>
<br>
[psum](man/psum.Rd) <center>Probability Outcomes for a Multinomial Trial</center>

<center> <h2>--Q--</h2> </center>
[qlaplace](man/qlaplace.Rd) <center>Laplace Quantiles</center>
<br>
[qlogF](man/qlogF.Rd) <center>Quantile of Log Distribution</center>
<br>
[qqplotc4s2](man/qqplotc4s2.Rd) <center>Population Quantile Plots</center>
<center> <h2>--R--</h2> </center>
[rcn](man/rcn.Rd) <center>Random Contaminated Normal Deviates</center>
<br>
[rscn](man/rscn.Rd) <center>Random Sample from Contaminatied Normal Distribution</center>

<center> <h2>--S--</h2> </center>
[simplegame](man/simplegame.Rd) <center>Simple Game for Estimation of Expected Gain</center>

<center> <h2>--T--</h2> </center>
[tpower2g2](man/tpower2g2.Rd) <center>Power Function Of The Two Sample Test</center>
<br>
[tpowerg](man/tpowerg.Rd) <center>Power of the One Sample t-Test</center>
<br>
[tpowerg2](man/tpowerg2.Rd) <center>Graphs a Two Sample T-Test</center>
<br>
[ttable](man/ttable.Rd) <center>t-Distribution Table</center>

<center> <h2>--W--</h2> </center>
[waldpois](man/waldpois.Rd) <center>Wald Test Statistic</center>
<br>
[wil2powsim](man/wil2powsim.Rd) <center>Wilcox Power Simulation</center>
